; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    SmartRC-CC1101-Driver-Lib
    tzapu/WiFiManager@^2.0.17
    vintlabs/FauxmoESP@^3.4.1
; Décommente ces lignes pour activer les logs de debug fauxmoESP (utile si Alexa ne détecte pas l'appareil)
;build_flags =
;    -D DEBUG_FAUXMO=Serial
;    -D DEBUG_FAUXMO_VERBOSE_TCP=true
;    -D DEBUG_FAUXMO_VERBOSE_UDP=true
